name: Docker Publish

on:
  push:
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '1 1 1 * *'  

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get date
        id: date
        run: echo "today=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          build-args: |
            RUNNER=github
          tags: |
            zcx2001/ubuntu-go:${{ steps.date.outputs.today }}
            zcx2001/ubuntu-go:latest